In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris =load_iris()

In [3]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [7]:
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print(type(iris['data']))

<class 'numpy.ndarray'>


In [9]:
print(iris['data'].shape)

(150, 4)


In [10]:
print(iris['data'][:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [11]:
print(iris['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, x_test, Y_train, y_test = train_test_split(iris['data'],iris['target'],random_state=0)

In [14]:
print(X_train.shape)
print(Y_train.shape)

(112, 4)
(112,)


In [15]:
print(x_test.shape)
print(y_test.shape)

(38, 4)
(38,)


In [17]:
iris_df = pd.DataFrame(X_train,columns=iris.feature_names)

In [18]:
from pandas.plotting import scatter_matrix

In [19]:
%matplotlib

Using matplotlib backend: MacOSX


In [22]:
scatter_matrix(iris_df, c=Y_train, figsize=(15,15),marker='o',hist_kwds={'bins':20},s=80,alpha=0.7)

array([[<AxesSubplot:xlabel='sepal length (cm)', ylabel='sepal length (cm)'>,
        <AxesSubplot:xlabel='sepal width (cm)', ylabel='sepal length (cm)'>,
        <AxesSubplot:xlabel='petal length (cm)', ylabel='sepal length (cm)'>,
        <AxesSubplot:xlabel='petal width (cm)', ylabel='sepal length (cm)'>],
       [<AxesSubplot:xlabel='sepal length (cm)', ylabel='sepal width (cm)'>,
        <AxesSubplot:xlabel='sepal width (cm)', ylabel='sepal width (cm)'>,
        <AxesSubplot:xlabel='petal length (cm)', ylabel='sepal width (cm)'>,
        <AxesSubplot:xlabel='petal width (cm)', ylabel='sepal width (cm)'>],
       [<AxesSubplot:xlabel='sepal length (cm)', ylabel='petal length (cm)'>,
        <AxesSubplot:xlabel='sepal width (cm)', ylabel='petal length (cm)'>,
        <AxesSubplot:xlabel='petal length (cm)', ylabel='petal length (cm)'>,
        <AxesSubplot:xlabel='petal width (cm)', ylabel='petal length (cm)'>],
       [<AxesSubplot:xlabel='sepal length (cm)', ylabel='petal width (c

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
knn= KNeighborsClassifier(n_neighbors=1)

In [25]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=1)

In [26]:
X_new=np.array([[5,2.9,1,0.2]])

In [27]:
X_new.shape

(1, 4)

In [30]:
guess = knn.predict(X_new)
print('Guess class: ',guess)
print('Guess type: ',iris['target_names'][guess])

Guess class:  [0]
Guess type:  ['setosa']


In [31]:
y_guess=knn.predict(x_test)
print(y_guess)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [32]:
print(np.mean(y_guess==y_test))

0.9736842105263158


In [34]:
print(knn.score(x_test,y_test))

0.9736842105263158
