In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('./student/student-mat.csv',sep=';')

In [3]:
data = data[['G1','G2','G3','studytime','failures','absences','age']]

In [4]:
data.head()

G1  G2  G3  studytime  failures  absences  age
0   5   6   6          2         0         6   18
1   5   5   6          2         0         4   17
2   7   8  10          2         3        10   15
3  15  14  15          3         0         2   15
4   6  10  10          2         0         4   16

In [6]:
data.rename(columns={'G1':'Grade1',
                    'G2':'Grade2',
                    'G3':'Final'},
           inplace=True)

In [8]:
data.dtypes

Grade1       int64
Grade2       int64
Final        int64
studytime    int64
failures     int64
absences     int64
age          int64
dtype: object

In [12]:
import numpy as np
y=np.array(data['Final'])
X=np.array(data.drop('Final',axis=1))

In [13]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
linear = LinearRegression()

In [23]:
linear.fit(X_train,y_train)

LinearRegression()

In [24]:
linear.score(X_test,y_test)

0.8325898318712226

In [25]:
linear.score(X_train,y_train)

0.8261275475197141

In [26]:
print('Coefficient: \n',linear.coef_)
print('Constant: \n', linear.intercept_)

Coefficient: 
 [ 0.19575962  0.95558174 -0.24215827  0.12730705  0.03566925 -0.23224281]
Constant: 
 2.1549097406751496


In [27]:
data.head()

Grade1  Grade2  Final  studytime  failures  absences  age
0       5       6      6          2         0         6   18
1       5       5      6          2         0         4   17
2       7       8     10          2         3        10   15
3      15      14     15          3         0         2   15
4       6      10     10          2         0         4   16

In [50]:
new_data = np.random.randint(0,20,size=(1,6))
linear.predict(new_data)

array([15.13518889])

In [51]:
new_data

array([[10, 16, 12,  7, 15, 12]])