In [3]:
print("Hello World")

Hello World


# Başlık1
## Başlık2
### Başlık3
deneme

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
import time

In [7]:
k = np.array([1,2,3,4,5,6])
k

array([1, 2, 3, 4, 5, 6])

In [8]:
start_time = time.time()
A= np.array(50000000)
A ** 2
time1 = time.time() - start_time
start_time2 = time.time()
L = range(50000000)
[i ** 2 for i in L]
time2 = time.time() - start_time2

print(time2/time1)

162180.0236886633


In [9]:
x = np.array([4,5,6,7])
print(x)

[4 5 6 7]


In [10]:
print(type(x))
print(x.shape)
print(x.size)
print(x.ndim)
print(x.nbytes)
print(x.dtype)

<class 'numpy.ndarray'>
(4,)
4
1
32
int64


In [11]:
t = np.array([[1,2,3],[4,5,6]])
y = t
print(y)
print(type(y))
print(y.shape)
print(y.size)
print(y.ndim)
print(y.nbytes)
print(y.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2
48
int64


In [12]:
z = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
y = z
print(y)
print(type(y))
print(y.shape)
print(y.size)
print(y.ndim)
print(y.nbytes)
print(y.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)
12
3
96
int64


In [13]:
x = np.array([1,"2",3])
print(x.dtype)

<U21


In [14]:
x = np.array([1,2.0,3], dtype=np.complex)
print(x.dtype)
print(x)

complex128
[1.+0.j 2.+0.j 3.+0.j]


In [15]:
x = np.array([1.2,2.7,3.8], dtype=np.int)
print(x)
print(x.dtype)

[1 2 3]
int64


In [16]:
x = np.array(x, dtype=float)
print(x)
print(x.dtype)

[1. 2. 3.]
float64


In [17]:
x = x.astype(np.int)
print(x)

[1 2 3]


In [18]:
x1 = np.array([1,2,3],dtype=np.int)
x2 = np.array([5.2,2.8,4.9],dtype=np.float)

print(x1+x2)
print((x1+x2).dtype)

[6.2 4.8 7.9]
float64


In [19]:
x = np.sqrt(np.array([-1,9,4], dtype=np.complex))
print(x)
print(x.dtype)
print(type(x))
print(x.real)
print(x.imag)
print(x.real.dtype)
print(x.imag.dtype)

[0.+1.j 3.+0.j 2.+0.j]
complex128
<class 'numpy.ndarray'>
[0. 3. 2.]
[1. 0. 0.]
float64
float64


In [20]:
np.save('ndarray_1',x)

In [21]:
y = np.load('ndarray_1.npy')
print(y)
print(y.shape)

[0.+1.j 3.+0.j 2.+0.j]
(3,)


In [22]:
x1 = np.zeros(4)
print(x1)
print(x1.dtype)
x2 = np.ones(4)
print(x2)
print(x2.dtype)

[0. 0. 0. 0.]
float64
[1. 1. 1. 1.]
float64


In [23]:
x1 = np.zeros((2,3,4), dtype=np.int)
print(x1)
print(x1.dtype)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
int64


In [24]:
x = np.full((2,3),10)
print(x)

[[10 10 10]
 [10 10 10]]


In [25]:
x = np.empty((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [26]:
x.fill(3)
print(x)

[[3. 3.]
 [3. 3.]]


In [27]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
y = np.eye(5,4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [29]:
x = np.eye(6)
print(x)
y = np.eye(6,k=3)
print(y)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [30]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
x = np.diag([3,4,7,11])
print(x)

[[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0  7  0]
 [ 0  0  0 11]]


In [32]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [34]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [35]:
x = np.linspace(0,15,10)
x

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [36]:
x = np.linspace(0,25, endpoint=False)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5])

In [37]:
x = np.arange(20)
print(x)

x = np.reshape(x, (4,5))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
x = np.linspace(0,19,20)
print(x)

y = np.reshape(x, (2,10))
print(y)
print(x.size)
print(y.size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
20
20


In [39]:
z = np.linspace(0,19,20).reshape(2,10)
print(z)


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [40]:
x = np.random.random((2,3))
x

array([[0.88714133, 0.34077978, 0.40109802],
       [0.32194499, 0.80178331, 0.75053335]])

In [41]:
x = np.random.randint(3,12, size=(3,2))
x

array([[ 9, 11],
       [ 9,  6],
       [ 8,  5]])

In [42]:
x = np.arange(5)
print(x)
print(x[2])
print(x[-3])

[0 1 2 3 4]
2
2


In [43]:
x[2] = 200
x

array([  0,   1, 200,   3,   4])

In [44]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
x[0,1]
x[0,3],x[2,2] = 300,600
x

array([[  0,   1,   2, 300],
       [  4,   5,   6,   7],
       [  8,   9, 600,  11]])

In [46]:
x = np.arange(6)
print(x)
y = np.delete(x, [0,3])
print(x)
print(y)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[1 2 4 5]


# axis = 0 -> row (satır), axis = 1 -> column (sütun)

In [47]:
x = np.arange(16).reshape(4,4)
print(x)
x = np.delete(x,1,axis=0)
print(x)
x = np.delete(x,1,axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  3]
 [ 8 10 11]
 [12 14 15]]


In [48]:
x = np.arange(16).reshape(4,4)
print(x)
x = np.delete(x, [0,2], axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [49]:
x = np.arange(5)
print(x)
x = np.append(x,100)
print(x)
x = np.append(x,[200,300])
print(x)

[0 1 2 3 4]
[  0   1   2   3   4 100]
[  0   1   2   3   4 100 200 300]


In [50]:
x = np.arange(9).reshape(3,3)
print(x)
x = np.append(x,[[100,200,300]], axis = 0)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


In [51]:
x = np.append(x,[[10],[20],[30],[40]], axis = 1)
print(x)

[[  0   1   2  10]
 [  3   4   5  20]
 [  6   7   8  30]
 [100 200 300  40]]


In [52]:
#np.insert ---> np.insert(ndarray, index, element, axis)
x = np.arange(5)
print(x)
x= np.insert(x,0,10)
print(x)

[0 1 2 3 4]
[10  0  1  2  3  4]


In [53]:
x= np.insert(x,2,[300,400])
print(x)

[ 10   0 300 400   1   2   3   4]


In [54]:
x = np.arange(9).reshape(3,3)
print(x)
y = np.insert(x,1,[100,200,300], axis=0)
print(y)
y = np.insert(x,0,[100,200,300], axis=1)
print(y)
y = np.insert(x,0,[100], axis=1)
print(y)
y = np.insert(x,0,[[100],[200]], axis=1)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]
[[100   0   1   2]
 [200   3   4   5]
 [300   6   7   8]]
[[100   0   1   2]
 [100   3   4   5]
 [100   6   7   8]]
[[100 200   0   1   2]
 [100 200   3   4   5]
 [100 200   6   7   8]]


In [55]:
x = np.arange(3)
print(x)

y = np.arange(9).reshape(3,3)
print(y)

z = np.vstack((x,y))
print(z)

y = y.reshape(9,)
print(y)

t = np.hstack((x,y))
print(t)

#np.stack

[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 0 1 2 3 4 5 6 7 8]


In [56]:
x = np.arange(10)
print(x)
print(x[2:6])
print(x[4:])
print(x[:7])
print(x[:-1])
print(x[-4:-2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]
[6 7]


In [57]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [58]:
x = np.arange(25).reshape(5,5)
print(x,"\n")
y = x[0:3,1:4]
print(y,"\n")

z = x[2:]
print(z,"\n")

t = x[::]
print(t,"\n")

v = x[:,3:]
print(v)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [59]:
x = np.arange(9).reshape(3,3)
print(x,"\n")

y = x[1:2,0:2]
print(y)
y[0,0] = 100
print(x,"\n")

print(np.shares_memory(x,y))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4]]
[[  0   1   2]
 [100   4   5]
 [  6   7   8]] 

True


In [60]:
x = np.arange(16).reshape(4,4)
print(x)
print()
y = np.copy(x[0:3,1:3])
print(y)
print()
y[0,1] = 500
print(x)
print()
print(y)
print()
z = x[1:2,1:2].copy()
print(z)
print(np.shares_memory(x,z))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[  1 500]
 [  5   6]
 [  9  10]]

[[5]]
False


In [61]:
x = np.linspace(1,19,10).reshape(2,5)
print(x.size)
print(x)

10
[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]]


In [62]:
x = np.linspace(1,21,11)
print(x.size)
print(x)
y = np.array([2,4,7])
print(y)
print(x[y])

11
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[2 4 7]
[ 5.  9. 15.]


In [63]:
x = np.arange(25).reshape(5,5)
print(x)
y = np.array([1,2])
print(y)
print()
print(x[y,:])

# fancy indexing

z = x[y,:]
print(z)
z[0,0] = 100
print()
print(z)
print()
print(x)

print(np.shares_memory(x,z))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[1 2]

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]

[[100   6   7   8   9]
 [ 10  11  12  13  14]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False


In [64]:
# boolean indezing

x = np.arange(10)
print(x)
print()
z = x[(x % 2 == 0)]
print(z)
print()
z[0] = 10
print(z)
print()
print(x)
print()

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]

[10  2  4  6  8]

[0 1 2 3 4 5 6 7 8 9]



In [65]:
x = np.random.randint(10,size=10)
y = np.random.randint(2,size=10)
print(x)
print(y)
print(x>y)
print(type(x>y))
print((x>y).dtype)

print(np.all(x>y))
print(np.any(x>y))

[1 5 1 2 6 9 6 4 5 4]
[1 0 1 1 1 1 1 0 1 0]
[False  True False  True  True  True  True  True  True  True]
<class 'numpy.ndarray'>
bool
False
True


In [66]:
x = np.linspace(1,21,11)
print(x)
mask = (x % 3 == 0)
print(mask)
print(type(mask))
print(x[mask])
x[mask] = 1
print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[False  True False False  True False False  True False False  True]
<class 'numpy.ndarray'>
[ 3.  9. 15. 21.]
[ 1.  1.  5.  7.  1. 11. 13.  1. 17. 19.  1.]


In [67]:
x = np.array([2,5,3,6,9])
y = np.array([6,1,8,7,3])

z = np.intersect1d(x,y)

print(type(z))

<class 'numpy.ndarray'>


In [68]:
print(np.setdiff1d(x,y))
print(np.setdiff1d(y,x))

[2 5 9]
[1 7 8]


In [69]:
print(np.union1d(x,y))

[1 2 3 5 6 7 8 9]


In [70]:
print(np.in1d(x,y))

[False False  True  True False]


In [71]:
x = np.array([2,5,3,6,9,4,3,6,5,0])
print(np.unique(x))

[0 2 3 4 5 6 9]


In [72]:
#sort

x = np.random.randint(1,10,size=(10,))
print(x)
print(np.sort(x))
print(x)
print()

y = np.random.randint(1,10, size=(10,))
print(y)
y.sort()
print(y)

[9 8 5 1 4 5 4 8 7 5]
[1 4 4 5 5 5 7 8 8 9]
[9 8 5 1 4 5 4 8 7 5]

[1 4 1 4 3 3 3 7 6 3]
[1 1 3 3 3 3 4 4 6 7]


In [73]:
x = np.random.randint(1,10, size = (5,5))
print(x)
print()
print(np.sort(x,axis=0))
print()
print(np.sort(x,axis=1))
print()

[[9 7 9 1 8]
 [2 3 2 4 1]
 [4 6 6 5 9]
 [1 2 7 6 4]
 [2 5 1 7 4]]

[[1 2 1 1 1]
 [2 3 2 4 4]
 [2 5 6 5 4]
 [4 6 7 6 8]
 [9 7 9 7 9]]

[[1 7 8 9 9]
 [1 2 2 3 4]
 [4 5 6 6 9]
 [1 2 4 6 7]
 [1 2 4 5 7]]



In [74]:
x = np.random.randint(1,10,size=(5,))
y = np.random.randint(1,10,size=(5,))
print(x)
print(y)

print(x+y)
print(np.add(x,y))
print(type(x+y))
print(type(np.add(x,y)))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

[5 6 5 2 2]
[5 2 7 4 4]
[10  8 12  6  6]
[10  8 12  6  6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 0  4 -2 -2 -2]
[ 0  4 -2 -2 -2]
[25 12 35  8  8]
[25 12 35  8  8]
[1.         3.         0.71428571 0.5        0.5       ]
[1.         3.         0.71428571 0.5        0.5       ]


In [75]:
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x == y)

[8 9 8 5 5]
[ 2  3  2 -1 -1]
[15 18 15  6  6]
[1.66666667 2.         1.66666667 0.66666667 0.66666667]
[ True False False False False]


In [76]:
print(np.array_equal(x,y))

False


In [77]:
print(np.sqrt(x))
print(np.power(x,3))
print(x)
print(np.exp(x))


[2.23606798 2.44948974 2.23606798 1.41421356 1.41421356]
[125 216 125   8   8]
[5 6 5 2 2]
[148.4131591  403.42879349 148.4131591    7.3890561    7.3890561 ]


In [78]:
x = np.random.randint(1,10,size=(3,3))
print(x)
print(np.sum(x))
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.min())
print(x.max())
print(x.argmin()) # min elemanın index sırası
print(x.argmax()) # max elemanın index sırası

[[3 6 8]
 [1 6 6]
 [5 6 4]]
45
[ 9 18 18]
[17 13 15]
1
8
3
2


In [79]:
x = np.random.randint(1,10,size=(8,))
print(x)
print()
print(x.mean())
print()
print(np.median(x))
print()
print(x.std())
print()

[1 9 6 2 1 1 2 1]

2.875

1.5

2.8034576865007255



In [80]:
y = np.random.randint(1,10,size=(4,3))
print(y)
print()
print(y.mean(axis=0))
print()
print(y.mean(axis=1))
print()
print(y.std(axis=0))

[[4 8 5]
 [6 3 5]
 [7 8 8]
 [1 9 7]]

[4.5  7.   6.25]

[5.66666667 4.66666667 7.66666667 5.66666667]

[2.29128785 2.34520788 1.29903811]


In [81]:
x = np.random.randint(1,10,size=(1,))
y = np.random.randint(1,10,size=(3,2))
print(x)
print()
print(y)
print()
print(x+y)

[9]

[[2 3]
 [5 6]
 [1 5]]

[[11 12]
 [14 15]
 [10 14]]


In [82]:
x = np.zeros(5)
y = np.ones(5)
print(x)
print(y)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [83]:
x = np.arange(7,42,2)
print(x)

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [84]:
x = np.linspace(1,10,16).reshape(4,4)
print(x)

[[ 1.   1.6  2.2  2.8]
 [ 3.4  4.   4.6  5.2]
 [ 5.8  6.4  7.   7.6]
 [ 8.2  8.8  9.4 10. ]]


In [85]:
x = np.random.randint(1,10,size=(4,4))
print(x)

[[5 1 2 4]
 [3 9 5 6]
 [5 1 9 4]
 [1 3 9 8]]


In [86]:
x = np.linspace(0.1,1,10)
print(x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [87]:
x = np.arange(25).reshape(5,5)
print(x[1:3,2:4])

[[ 7  8]
 [12 13]]


In [88]:
x = np.arange(1,17).reshape(4,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [89]:
y = x[:,[1,3]].reshape(2,4) 
# y = x[x%2==0].reshaper(2,4)
print(y)

[[ 2  4  6  8]
 [10 12 14 16]]


In [90]:
A = np.array([[1,1],[5,10]])
B = np.array([100,700])
print(A)
print()
print(B)
print()
x = np.linalg.solve(A,B)
print(x)

[[ 1  1]
 [ 5 10]]

[100 700]

[60. 40.]


In [91]:
x = np.random.randint(1,5,4)
print(x)
y = np.random.randint(1,5,4)
print(y)
print()
print(np.dot(x,y))

[3 1 3 1]
[2 1 3 1]

17


In [92]:
x = np.random.randint(1,5,size = (2,2))
print(x)
y = np.random.randint(1,5,size = (2,2))
print(y)
print()
print(np.dot(x,y))

[[4 3]
 [1 4]]
[[1 3]
 [1 3]]

[[ 7 21]
 [ 5 15]]


In [93]:
print(pd.__version__)

1.1.4


In [94]:
student = ['Arin',23,'CE']
print(student)
print(type(student))

print()

ps_student = pd.Series(student)
print(ps_student)
print(type(ps_student))

['Arin', 23, 'CE']
<class 'list'>

0    Arin
1      23
2      CE
dtype: object
<class 'pandas.core.series.Series'>


In [95]:
student = {
    'name': 'Arin',
    'age' : 23,
    'department': 'CE'
}
print(student)
print(type(student))
print()

ps_student = pd.Series(student)
print(ps_student)
print(type(ps_student))

{'name': 'Arin', 'age': 23, 'department': 'CE'}
<class 'dict'>

name          Arin
age             23
department      CE
dtype: object
<class 'pandas.core.series.Series'>


In [96]:
student = pd.Series(['Arin', 23, 'CE'])
print(student)
print(type(student))

0    Arin
1      23
2      CE
dtype: object
<class 'pandas.core.series.Series'>


In [97]:
numbers = pd.Series([24,37,43])
print(numbers)
print(type(numbers))

0    24
1    37
2    43
dtype: int64
<class 'pandas.core.series.Series'>


In [98]:
booleans = pd.Series([True,False,True])
print(booleans)
print(type(booleans))

0     True
1    False
2     True
dtype: bool
<class 'pandas.core.series.Series'>


In [99]:
student = pd.Series(data=['Arin', 23, 'CE'], index = ['name','age','department'])
print(student)
print()
print(type(student))
print()
print(student.values)
print()
print(student.index)
print()
print(student.shape)
print()
print(student.ndim)
print()
print(student.size)
print()
student.name = 'test'
print(student.name)
print()
print(student.dtype)
print()

name          Arin
age             23
department      CE
dtype: object

<class 'pandas.core.series.Series'>

['Arin' 23 'CE']

Index(['name', 'age', 'department'], dtype='object')

(3,)

1

3

test

object



In [100]:
x = 'name' in student
print(x)

y = 'job' in student
print(y)

True
False


In [101]:
x = 'Ahmet' in student.values
print(x)
y = 'Arin' in student.values
print(y)

False
True


In [102]:
numbers = pd.Series([4,2.5,2])
print(numbers)
print(numbers.sum())
print(numbers.mean())
print(numbers.product())

0    4.0
1    2.5
2    2.0
dtype: float64
8.5
2.8333333333333335
20.0


In [103]:
student = pd.Series(data=['Arin','Software',23,'CE'], index = ['name','surname','age','department'])
print(student)

name              Arin
surname       Software
age                 23
department          CE
dtype: object


In [104]:
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype=None,
    name=None,
    copy=False,
    fastpath=False,
)
Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, *, **) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series.

    .. versionchanged:: 0.23.0
       If data is a dict, argument order is maintained for Python 3.6
       and later.

index : array-like or Index (1d)
    Values must 

In [105]:
print(student[['name','age']])
print('---------------------------------------------')
print(type(student[['name','age']]))
print('---------------------------------------------')
print(student[1])
print('---------------------------------------------')
print(student[[0,2]])
print('---------------------------------------------')
print(student[0:2])
print('---------------------------------------------')
print(student[-2])
print('---------------------------------------------')
print(student[0:])
print('---------------------------------------------')
print(student[-2:])
print('---------------------------------------------')
print(student['name':'department'])

name    Arin
age       23
dtype: object
---------------------------------------------
<class 'pandas.core.series.Series'>
---------------------------------------------
Software
---------------------------------------------
name    Arin
age       23
dtype: object
---------------------------------------------
name           Arin
surname    Software
dtype: object
---------------------------------------------
23
---------------------------------------------
name              Arin
surname       Software
age                 23
department          CE
dtype: object
---------------------------------------------
age           23
department    CE
dtype: object
---------------------------------------------
name              Arin
surname       Software
age                 23
department          CE
dtype: object


In [106]:
#loc -> location, iloc -> index location

print(student.loc['age'])
print('---------------------------------------------')
print(student.iloc[0:2])
print('---------------------------------------------')
print(student.iloc[2])

23
---------------------------------------------
name           Arin
surname    Software
dtype: object
---------------------------------------------
23


In [107]:
print(student)
print()
student['name']='Elis'
print(student)
student.iloc[2]=15
print(student)

# Pandas Series --> mutable

name              Arin
surname       Software
age                 23
department          CE
dtype: object

name              Elis
surname       Software
age                 23
department          CE
dtype: object
name              Elis
surname       Software
age                 15
department          CE
dtype: object


In [108]:
student2 = student.drop('name')
print('---------------------------------------------')
print(student)
print('---------------------------------------------')
print(student2)
print('---------------------------------------------')
student2.drop('age', inplace=True)
print(student2)

---------------------------------------------
name              Elis
surname       Software
age                 15
department          CE
dtype: object
---------------------------------------------
surname       Software
age                 15
department          CE
dtype: object
---------------------------------------------
surname       Software
department          CE
dtype: object


In [109]:
print(len(student))
print('---------------------------------------------')
print(list(student))
print('---------------------------------------------')
print(dict(student))
print('---------------------------------------------')
print(sorted(student2))

4
---------------------------------------------
['Elis', 'Software', 15, 'CE']
---------------------------------------------
{'name': 'Elis', 'surname': 'Software', 'age': 15, 'department': 'CE'}
---------------------------------------------
['CE', 'Software']


In [110]:
student = pd.Series(data=['Arin','Software','CE'], index = ['name','surname','department'])
print(student)
print('---------------------------------------------')
print(sorted(student))
print('---------------------------------------------')
print(max(student))
print('---------------------------------------------')
print(min(student))

name              Arin
surname       Software
department          CE
dtype: object
---------------------------------------------
['Arin', 'CE', 'Software']
---------------------------------------------
Software
---------------------------------------------
Arin


In [111]:
import csv

In [112]:
review_content = pd.read_csv('./ReviewContent.csv',usecols=['Review ID'], squeeze=True, encoding='utf-8',engine='python')
print(type(review_content))

<class 'pandas.core.series.Series'>


In [113]:
print(review_content)

0       4055629
1      25329416
2      21705849
3      41133812
4       7465026
         ...   
995    44498863
996    30544438
997    46642535
998    21403195
999    38944752
Name: Review ID, Length: 1000, dtype: int64


In [114]:
print(review_content.head(10)) #default 5 veri

0     4055629
1    25329416
2    21705849
3    41133812
4     7465026
5    11372151
6    20417380
7    10787310
8    37085487
9    15542291
Name: Review ID, dtype: int64


In [115]:
print(review_content.tail(10)) #default 5 veri

990    32907620
991    35585745
992    13423090
993    27392171
994    28605533
995    44498863
996    30544438
997    46642535
998    21403195
999    38944752
Name: Review ID, dtype: int64


In [116]:
print(review_content.head(10))
print('---------------------------------------------')
print(review_content.sort_values().head(10)) 
print('---------------------------------------------')
print(review_content.head(10)) #kalıcı sıralama
print('---------------------------------------------')
review_content.sort_values(inplace=True)
print('---------------------------------------------')
print(review_content.sort_values(ascending=False).tail(10))

0     4055629
1    25329416
2    21705849
3    41133812
4     7465026
5    11372151
6    20417380
7    10787310
8    37085487
9    15542291
Name: Review ID, dtype: int64
---------------------------------------------
516     41756
535     67176
766     97586
741    123549
560    151811
847    205942
188    432284
65     443786
954    499085
453    503200
Name: Review ID, dtype: int64
---------------------------------------------
0     4055629
1    25329416
2    21705849
3    41133812
4     7465026
5    11372151
6    20417380
7    10787310
8    37085487
9    15542291
Name: Review ID, dtype: int64
---------------------------------------------
---------------------------------------------
453    503200
954    499085
65     443786
188    432284
847    205942
560    151811
741    123549
766     97586
535     67176
516     41756
Name: Review ID, dtype: int64


In [117]:
review_content.sort_index(ascending=False,inplace=True)
print(review_content.head())
print('---------------------------------------------')
review_content.sort_index(ascending=True,inplace=True)
print(review_content.head())

999    38944752
998    21403195
997    46642535
996    30544438
995    44498863
Name: Review ID, dtype: int64
---------------------------------------------
0     4055629
1    25329416
2    21705849
3    41133812
4     7465026
Name: Review ID, dtype: int64


In [118]:
print(review_content[4:8])
print('---------------------------------------------')
print(review_content.get(4))
print('---------------------------------------------')
#print(review_content[1004]) -> hata
print('---------------------------------------------')
print(review_content.get(1004, default='Eleman Yok!'))
print('---------------------------------------------')
print(type(review_content.get(4)))
print('---------------------------------------------')
print(type(review_content.get(4)))
print('---------------------------------------------')
print(type(review_content.get([0,4])))
print('---------------------------------------------')

4     7465026
5    11372151
6    20417380
7    10787310
Name: Review ID, dtype: int64
---------------------------------------------
7465026
---------------------------------------------
---------------------------------------------
Eleman Yok!
---------------------------------------------
<class 'numpy.int64'>
---------------------------------------------
<class 'numpy.int64'>
---------------------------------------------
<class 'pandas.core.series.Series'>
---------------------------------------------


In [119]:
students = [
    {
        'name':'arin',
        'age':21,
        'gender':'F'
    },
    {
        'name':'fatih',
        'age':20,
        'gender':'M'
    },
    {
        'name':'elis',
        'age':24,
        'gender':'F'
    }
]
print(students)
print('---------------------------------------------')
print(type(students))
print('---------------------------------------------')
df_students = pd.DataFrame(students)
print('---------------------------------------------')
print(df_students)
print('---------------------------------------------')
print(type(df_students))
print('---------------------------------------------')


[{'name': 'arin', 'age': 21, 'gender': 'F'}, {'name': 'fatih', 'age': 20, 'gender': 'M'}, {'name': 'elis', 'age': 24, 'gender': 'F'}]
---------------------------------------------
<class 'list'>
---------------------------------------------
---------------------------------------------
    name  age gender
0   arin   21      F
1  fatih   20      M
2   elis   24      F
---------------------------------------------
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------


In [120]:
teachers= {
    'names': ['ahmet','cansu', 'hakan'],
    'ages': [41,36, 40],
    'gender': ['M','F', 'M'],
}
print('---------------------------------------------')
print(teachers)
print('---------------------------------------------')
print(type(teachers))
df_teachers = pd.DataFrame(teachers)
print('---------------------------------------------')
print(df_teachers)
print('---------------------------------------------')
print(type(df_teachers))
print('---------------------------------------------')

---------------------------------------------
{'names': ['ahmet', 'cansu', 'hakan'], 'ages': [41, 36, 40], 'gender': ['M', 'F', 'M']}
---------------------------------------------
<class 'dict'>
---------------------------------------------
   names  ages gender
0  ahmet    41      M
1  cansu    36      F
2  hakan    40      M
---------------------------------------------
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------


In [121]:
list_of_list= [
    ['ahmet','mehmet', 'ayşe'],
    [44, 39, 51],
]
print('---------------------------------------------')
print(list_of_list)
print('---------------------------------------------')
print(type(list_of_list))
df_list_of_list = pd.DataFrame(list_of_list)
print('---------------------------------------------')
print(df_list_of_list)
print('---------------------------------------------')
print(type(df_list_of_list))
print('---------------------------------------------')

---------------------------------------------
[['ahmet', 'mehmet', 'ayşe'], [44, 39, 51]]
---------------------------------------------
<class 'list'>
---------------------------------------------
       0       1     2
0  ahmet  mehmet  ayşe
1     44      39    51
---------------------------------------------
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------


In [122]:
names = ['ahmet', 'mahmut', 'fatih']
print(names)
print(type(names))

df_names = pd.DataFrame(names)
print()
print(df_names)
print(type(df_names))
print(df_names.ndim)

['ahmet', 'mahmut', 'fatih']
<class 'list'>

        0
0   ahmet
1  mahmut
2   fatih
<class 'pandas.core.frame.DataFrame'>
2


In [123]:
students = {'name': 'hale', 'age': 24'}
print(students)
print(type(students))

df_students = pd.DataFrame(students)

SyntaxError: EOL while scanning string literal (<ipython-input-123-75c8845d6be5>, line 1)

In [124]:
students = {'Hale':pd.Series(data=[25,'F','CE',172], index=['age','gender','department','height']),
            'Ahmet':pd.Series(data=[32,'M','EE',83], index=['age','gender','department','weight'])}
print(students)
print('---------------------------------------------')
print(type(students))
print('---------------------------------------------')
df_students = pd.DataFrame(students)
print('---------------------------------------------')
print(df_students)
print('---------------------------------------------')
print(type(df_students))

{'Hale': age            25
gender          F
department     CE
height        172
dtype: object, 'Ahmet': age           32
gender         M
department    EE
weight        83
dtype: object}
---------------------------------------------
<class 'dict'>
---------------------------------------------
---------------------------------------------
           Hale Ahmet
age          25    32
department   CE    EE
gender        F     M
height      172   NaN
weight      NaN    83
---------------------------------------------
<class 'pandas.core.frame.DataFrame'>


In [125]:
students = {'Hale':pd.Series(data=[25,'F','CE',172], index=['age','gender','department','height']),
            'Ahmet':pd.Series(data=[32,'M','EE',83], index=['age','gender','department','height']),
            'Fatma':pd.Series(data=[40,'F','TT',55], index=['age','gender','department','height'])}
df_students = pd.DataFrame(students)
print(df_students)
print('---------------------------------------------')
df_students2 = pd.DataFrame(students, columns=['Hale','Ahmet'])
print(df_students2)
print('---------------------------------------------')
df_students3 = pd.DataFrame(students, index=['age','gender'])
print(df_students3)
print('---------------------------------------------')
df_students4 = pd.DataFrame(students,columns=['Hale','Ahmet'], index=['department','height'])
print(df_students4)


           Hale Ahmet Fatma
age          25    32    40
gender        F     M     F
department   CE    EE    TT
height      172    83    55
---------------------------------------------
           Hale Ahmet
age          25    32
gender        F     M
department   CE    EE
height      172    83
---------------------------------------------
       Hale Ahmet Fatma
age      25    32    40
gender    F     M     F
---------------------------------------------
           Hale Ahmet
department   CE    EE
height      172    83


In [126]:
# Series
print(df_students['Ahmet'])
print(type(df_students['Ahmet']))

age           32
gender         M
department    EE
height        83
Name: Ahmet, dtype: object
<class 'pandas.core.series.Series'>


In [127]:
# DataFrame
print(df_students[['Ahmet']])
print(type(df_students[['Ahmet']]))

           Ahmet
age           32
gender         M
department    EE
height        83
<class 'pandas.core.frame.DataFrame'>


In [128]:
print(df_students[['Ahmet','Hale']])
print(type(df_students[['Ahmet','Hale']]))

           Ahmet Hale
age           32   25
gender         M    F
department    EE   CE
height        83  172
<class 'pandas.core.frame.DataFrame'>


In [129]:
print(df_students.loc['age'])
print(type(df_students.loc['age']))

Hale     25
Ahmet    32
Fatma    40
Name: age, dtype: object
<class 'pandas.core.series.Series'>


In [130]:
print(df_students.loc[['age','gender']])
print('---------------------------------------------')
print(type(df_students.loc[['age','gender']]))

       Hale Ahmet Fatma
age      25    32    40
gender    F     M     F
---------------------------------------------
<class 'pandas.core.frame.DataFrame'>


In [131]:
print(df_students['Hale']['age'])
print(df_students['Fatma']['department'])

25
TT


In [132]:
df_students['Fatih'] = [17,'M','ELH',190]
print(df_students)

df_students['Fatih2'] = df_students['Fatma'] + df_students['Fatih']
print(df_students)

           Hale Ahmet Fatma Fatih
age          25    32    40    17
gender        F     M     F     M
department   CE    EE    TT   ELH
height      172    83    55   190
           Hale Ahmet Fatma Fatih Fatih2
age          25    32    40    17     57
gender        F     M     F     M     FM
department   CE    EE    TT   ELH  TTELH
height      172    83    55   190    245


In [133]:
new_row = pd.DataFrame({'Hale':'kurek', 'Ahmet':'manav','Fatma':'yolcu'}, index=['surname'])
df_students = df_students.append(new_row)
print(df_students)

             Hale  Ahmet  Fatma Fatih Fatih2
age            25     32     40    17     57
gender          F      M      F     M     FM
department     CE     EE     TT   ELH  TTELH
height        172     83     55   190    245
surname     kurek  manav  yolcu   NaN    NaN


In [134]:
# pop -> col
# drop -> col - row (axis)

df_students.pop('Ahmet')
print(df_students)

df_students = df_students.drop('Hale', axis=1)

             Hale  Fatma Fatih Fatih2
age            25     40    17     57
gender          F      F     M     FM
department     CE     TT   ELH  TTELH
height        172     55   190    245
surname     kurek  yolcu   NaN    NaN


In [135]:
print(df_students)

            Fatma Fatih Fatih2
age            40    17     57
gender          F     M     FM
department     TT   ELH  TTELH
height         55   190    245
surname     yolcu   NaN    NaN


In [136]:
df_students = df_students.drop(['Fatih2','Fatma'], axis=1)
print(df_students)

           Fatih
age           17
gender         M
department   ELH
height       190
surname      NaN


In [137]:
students = {'Hale':pd.Series(data=[25,'Cetin','CE',161], index=['age','surname','department','height']),
            'Ahmet':pd.Series(data=[32,'M','EE',83], index=['age','gender','department','weight']),
            'Fatma':pd.Series(data=[40,'Gulsen','TT',175], index=['age','surname','department','height'])}
df_students = pd.DataFrame(students)
print(df_students)
print('---------------------------------------------')
# isnull
x = df_students.isnull()
print(x)
print(type(x))
print('---------------------------------------------')
z = x[(x == False)]
print(z)
print('---------------------------------------------')
# stunlardaki null sayısı
y = df_students.isnull().sum() 
print(y)
print(type(y))
print('---------------------------------------------')
# toplam null sayısı
z = df_students.isnull().sum().sum()
print(z)
print(type(z))


             Hale Ahmet   Fatma
age            25    32      40
department     CE    EE      TT
gender        NaN     M     NaN
height        161   NaN     175
surname     Cetin   NaN  Gulsen
weight        NaN    83     NaN
---------------------------------------------
             Hale  Ahmet  Fatma
age         False  False  False
department  False  False  False
gender       True  False   True
height      False   True  False
surname     False   True  False
weight       True  False   True
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------
            Hale  Ahmet  Fatma
age          0.0    0.0    0.0
department   0.0    0.0    0.0
gender       NaN    0.0    NaN
height       0.0    NaN    0.0
surname      0.0    NaN    0.0
weight       NaN    0.0    NaN
---------------------------------------------
Hale     2
Ahmet    2
Fatma    2
dtype: int64
<class 'pandas.core.series.Series'>
---------------------------------------------
6
<class 'numpy.int64'>


In [138]:
print('---------------------------------------------')
# not null
t = df_students.notnull()
print(t)
print(type(t))
print('---------------------------------------------')
# stunlardaki boş olmayan sayısı
k = df_students.notnull().sum() 
print(k)
print(type(k))
print('---------------------------------------------')
# toplam boş olmayan sayısı
l = df_students.notnull().sum().sum()
print(l)
print(type(l))
print('---------------------------------------------')

---------------------------------------------
             Hale  Ahmet  Fatma
age          True   True   True
department   True   True   True
gender      False   True  False
height       True  False   True
surname      True  False   True
weight      False   True  False
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------
Hale     4
Ahmet    4
Fatma    4
dtype: int64
<class 'pandas.core.series.Series'>
---------------------------------------------
12
<class 'numpy.int64'>
---------------------------------------------


In [139]:
print('---------------------------------------------')
# count
t = df_students.count()
print(t)
print(type(t))
print('---------------------------------------------')
# stunlardaki boş olmayan sayısı
k = df_students.count().sum() 
print(k)
print(type(k))
print('---------------------------------------------')
# toplam boş olmayan sayısı
l = df_students.count().sum().sum()
print(l)
print(type(l))
print('---------------------------------------------')

---------------------------------------------
Hale     4
Ahmet    4
Fatma    4
dtype: int64
<class 'pandas.core.series.Series'>
---------------------------------------------
12
<class 'numpy.int64'>
---------------------------------------------
12
<class 'numpy.int64'>
---------------------------------------------


In [140]:
print('---------------------------------------------')
#nan olan satırlar siliniyor
x = df_students.dropna()
print(x)
print(type(x))
print('---------------------------------------------')
print(df_students)
print('---------------------------------------------')
#tüm veriler 'nan olunca'
df_students['Ahmet']['weight'] = np.nan #veya Null
x = df_students.dropna(how="all")
print(x)
print(type(x))
print('---------------------------------------------')
# thresh'e eşit veya daha büyük nan varsa gösterme
x = df_students.dropna(thresh=2)
print(x)
print(type(x))
print('---------------------------------------------')
x = df_students.dropna(axis=0)
print(x)
print(type(x))
print('---------------------------------------------')
x = df_students.dropna(axis=1)
print(x)
print(type(x))
print('---------------------------------------------')
x = df_students.dropna(axis=1,thresh=3)
print(x)
print(type(x))

---------------------------------------------
           Hale Ahmet Fatma
age          25    32    40
department   CE    EE    TT
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------
             Hale Ahmet   Fatma
age            25    32      40
department     CE    EE      TT
gender        NaN     M     NaN
height        161   NaN     175
surname     Cetin   NaN  Gulsen
weight        NaN    83     NaN
---------------------------------------------
             Hale Ahmet   Fatma
age            25    32      40
department     CE    EE      TT
gender        NaN     M     NaN
height        161   NaN     175
surname     Cetin   NaN  Gulsen
<class 'pandas.core.frame.DataFrame'>
---------------------------------------------
             Hale Ahmet   Fatma
age            25    32      40
department     CE    EE      TT
height        161   NaN     175
surname     Cetin   NaN  Gulsen
<class 'pandas.core.frame.DataFrame'>
------------------------------------------

In [141]:
df_students.dropna?

Signature:
df_students.dropna(
    axis=0,
    how='any',
    thresh=None,
    subset=None,
    inplace=False,
)
Docstring:
Remove missing values.

See the :ref:`User Guide <missing_data>` for more on which values are
considered missing, and how to work with missing data.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    Determine if rows or columns which contain missing values are
    removed.

    * 0, or 'index' : Drop rows which contain missing values.
    * 1, or 'columns' : Drop columns which contain missing value.

    .. versionchanged:: 1.0.0

       Pass tuple or list to drop on multiple axes.
       Only a single axis is allowed.

how : {'any', 'all'}, default 'any'
    Determine if row or column is removed from DataFrame, when we have
    at least one NA or all NA.

    * 'any' : If any NA values are present, drop that row or column.
    * 'all' : If all values are NA, drop that row or column.

thresh : int, optional
    Require that many non-NA va

In [142]:
#fill na default br önceki değeri koy (satır) (ffill)
x = df_students.fillna(method='ffill',axis=0)
print(x)
print('---------------------------------------------')
#sütun
x = df_students.fillna(method='ffill',axis=1)
print(x)
print('---------------------------------------------')
#bir sonraki sütun (backfill)
x = df_students.fillna(method='backfill',axis=0)
print(x)
print('---------------------------------------------')
print('---------------------------------------------')
print('---------------------------------------------')

             Hale Ahmet   Fatma
age            25    32      40
department     CE    EE      TT
gender         CE     M      TT
height        161     M     175
surname     Cetin     M  Gulsen
weight      Cetin     M  Gulsen
---------------------------------------------
             Hale  Ahmet   Fatma
age            25     32      40
department     CE     EE      TT
gender        NaN      M       M
height        161    161     175
surname     Cetin  Cetin  Gulsen
weight        NaN    NaN     NaN
---------------------------------------------
             Hale Ahmet   Fatma
age            25    32      40
department     CE    EE      TT
gender        161     M     175
height        161   NaN     175
surname     Cetin   NaN  Gulsen
weight        NaN   NaN     NaN
---------------------------------------------
---------------------------------------------
---------------------------------------------


In [143]:
review = pd.read_csv('./ReviewContent.csv')
print(review.head())

   Review ID Review Date                                     Review Content  \
0    4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
1   25329416  2013-11-03  Me and my friends had such a nice time at Dott...   
2   21705849  2014-11-27  I stayed for 4night.She gave us a lot of snuck...   
3   41133812  2012-05-08  The apartment was situated on the first floor ...   
4    7465026  2013-08-16  Even though it was only for one night, we had ...   

                         Listing Title            Neighbourhood  \
0  Nottinghill Portobello  Artist Flat   Kensington and Chelsea   
1   Quiet Pink Studio in the PIJP area  De Pijp - Rivierenbuurt   
2  PRIVATE Room in Spacious, Quiet Apt                   Harlem   
3       Bonito estudio en pleno centro              Universidad   
4        Acropolis Apartment brand new                 ΑΚΡΟΠΟΛΗ   

            City                State          Country        Room Type  \
0         London              England   United 

In [144]:
print(type(review))
print()
print(review.info())
print('---------------------------------------------')
print(review.dtypes)
print('---------------------------------------------')
print(review.ndim)
print('---------------------------------------------')
print(review.columns)
print('---------------------------------------------')
print(type(review.columns))
print('---------------------------------------------')
print(review.memory_usage())

<class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Review ID          1000 non-null   int64 
 1   Review Date        1000 non-null   object
 2   Review Content     999 non-null    object
 3   Listing Title      1000 non-null   object
 4   Neighbourhood      1000 non-null   object
 5   City               1000 non-null   object
 6   State              1000 non-null   object
 7   Country            1000 non-null   object
 8   Room Type          1000 non-null   object
 9   Room Price         1000 non-null   int64 
 10  Room Availability  1000 non-null   int64 
dtypes: int64(3), object(8)
memory usage: 86.1+ KB
None
---------------------------------------------
Review ID             int64
Review Date          object
Review Content       object
Listing Title        object
Neighbourhood        object
Ci

In [145]:
print(review["Room Price"].sum())
print('---------------------------------------------')
print(review.sum())
print('---------------------------------------------')
print(review["Room Availability"])
print('---------------------------------------------')
print(review["Room Availability"].add(10))
print('---------------------------------------------')
print(review["Room Availability"]+10)
#sum, sub, mul, div, +, -, *, /

118048
---------------------------------------------
Review ID                                                  23758497050
Review Date          2012-10-062013-11-032014-11-272012-05-082013-0...
Listing Title        Nottinghill Portobello  Artist FlatQuiet Pink ...
Neighbourhood        Kensington and ChelseaDe Pijp - RivierenbuurtH...
City                 LondonAmsterdamNew York CityMadridAthensPortla...
State                EnglandNorth HollandNew YorkComunidad de Madri...
Country              United KingdomThe NetherlandsUnited StatesSpai...
Room Type            Entire home/aptPrivate roomPrivate roomEntire ...
Room Price                                                      118048
Room Availability                                               253651
dtype: object
---------------------------------------------
0      338
1       10
2      268
3      274
4      281
      ... 
995    329
996    309
997     10
998    357
999    329
Name: Room Availability, Length: 1000, dtype: int64
----

In [146]:
print(review['City'])
print('---------------------------------------------')
print(review['City'].value_counts())
print('---------------------------------------------')
print(review['Room Type'].value_counts())
print('---------------------------------------------')
print(review['Room Price'].value_counts())
print('---------------------------------------------')
print(review['Room Price'].sort_values(ascending= False).head())
print('---------------------------------------------')
print(review['City'].sort_values())
print('---------------------------------------------')
print(review.sort_values("Room Price"))

0             London
1          Amsterdam
2      New York City
3             Madrid
4             Athens
           ...      
995            Paris
996      Los Angeles
997           Boston
998    New York City
999    New York City
Name: City, Length: 1000, dtype: object
---------------------------------------------
New York City    135
London           104
Paris            101
Los Angeles       68
Barcelona         61
San Francisco     59
Berlin            56
Amsterdam         45
Sydney            33
Portland          28
Madrid            28
Montreal          27
Seattle           23
Toronto           23
Brussels          23
Austin            22
New Orleans       22
Chicago           21
Venice            21
Boston            21
Washington        18
Melbourne         14
Vienna            14
Nashville         13
Athens            10
Antwerp            5
Oakland            5
Name: City, dtype: int64
---------------------------------------------
Entire home/apt    648
Private room       340

In [147]:
review = pd.read_csv('./ReviewContent.csv')

In [154]:
print(review["City"])
print(review["City"] == "London")
print("----------------------------------------")
print(review[review["City"] == "London"])

0             London
1          Amsterdam
2      New York City
3             Madrid
4             Athens
           ...      
995            Paris
996      Los Angeles
997           Boston
998    New York City
999    New York City
Name: City, Length: 1000, dtype: object
0       True
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Name: City, Length: 1000, dtype: bool
----------------------------------------
     Review ID Review Date                                     Review Content  \
0      4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
7     10787310  2013-06-02  Carolines room is perfectly located to discove...   
10    24326991  2014-10-19  Many thanks Annabel, our stay was perfect! We ...   
20    38360407  2013-12-31  Nice contact. Very friendly and supportive. Th...   
27    37847700  2014-02-02  Wannie was very accommodating and allowed us t...   
..         ...       

In [161]:
mask = review["City"] == "London"
print("----------------------------------------")
print(review[mask])
print("----------------------------------------")
mask = review["Room Type"] == "Private room"
print(review[mask])
print("----------------------------------------")
print(type(mask))


----------------------------------------
     Review ID Review Date                                     Review Content  \
0      4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
7     10787310  2013-06-02  Carolines room is perfectly located to discove...   
10    24326991  2014-10-19  Many thanks Annabel, our stay was perfect! We ...   
20    38360407  2013-12-31  Nice contact. Very friendly and supportive. Th...   
27    37847700  2014-02-02  Wannie was very accommodating and allowed us t...   
..         ...         ...                                                ...   
943   30716660  2013-04-21  The flat was very clean and centrally located....   
963   37527770  2012-08-16  Karen was a great host! She was extremely frie...   
966   11444280  2013-04-01  You couldn't ask for friendlier hosts! I had a...   
967   31488970  2014-10-18  Serena was very welcoming and the place was qu...   
971   21709517  2013-07-03  Anders is a great host. The flat is exac

In [162]:
mask1 = review["Room Price"] > 60
mask2 = review["Room Price"] < 100

mask = mask1 & mask2
print(review[mask])

     Review ID Review Date                                     Review Content  \
1     25329416  2013-11-03  Me and my friends had such a nice time at Dott...   
4      7465026  2013-08-16  Even though it was only for one night, we had ...   
8     37085487  2014-06-27  We had a great stay in Tyler's apartment. The ...   
17     7568387  2013-02-01  Kristina and Ekaterine were lovley hosts. They...   
20    38360407  2013-12-31  Nice contact. Very friendly and supportive. Th...   
..         ...         ...                                                ...   
992   13423090  2014-12-25  Ca' di paolo is a cozy apartment in a great lo...   
993   27392171  2012-03-07  What a great place to stay! In the heart of Ma...   
994   28605533  2014-09-24  We had a wonderful stay at this apartment. Alt...   
997   46642535  2014-08-30  John was a great host.  I came in on a red eye...   
998   21403195  2014-12-26  Very good experiance had a comfortable stay. V...   

                           

In [163]:
mask1 = review["Room Price"] > 200
mask2 = review["Room Availability"] > 300

mask = mask1 | mask2
print(review[mask])

     Review ID Review Date                                     Review Content  \
0      4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
6     20417380  2013-11-07  Wonderful experience. We loved staying in the ...   
7     10787310  2013-06-02  Carolines room is perfectly located to discove...   
8     37085487  2014-06-27  We had a great stay in Tyler's apartment. The ...   
9     15542291  2013-12-28  What a wonderful location, right in the heart ...   
..         ...         ...                                                ...   
992   13423090  2014-12-25  Ca' di paolo is a cozy apartment in a great lo...   
995   44498863  2012-08-30  I loved staying here during my time in Paris. ...   
996   30544438  2013-02-28  Highly recommend this as a place to stay if yo...   
998   21403195  2014-12-26  Very good experiance had a comfortable stay. V...   
999   38944752  2013-10-15  Thank you for the wonderful stay!   It was a c...   

                           

In [172]:
mask = (review["City"] == "Madrid") | (review["City"] == "London") | (review["City"] == "Amsterdam")
print(review[mask])

     Review ID Review Date                                     Review Content  \
0      4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
1     25329416  2013-11-03  Me and my friends had such a nice time at Dott...   
3     41133812  2012-05-08  The apartment was situated on the first floor ...   
7     10787310  2013-06-02  Carolines room is perfectly located to discove...   
10    24326991  2014-10-19  Many thanks Annabel, our stay was perfect! We ...   
..         ...         ...                                                ...   
967   31488970  2014-10-18  Serena was very welcoming and the place was qu...   
970    1211808  2014-03-08  It was such a shame that we were only able to ...   
971   21709517  2013-07-03  Anders is a great host. The flat is exactly as...   
985   29498170  2013-12-17  The neighborhood was pretty central and my fri...   
987   21950610  2013-06-10  Arne's studio was the perfect size and locatio...   

                           

In [174]:
mask = review["City"].isin(["Madrid","London","Amsterdam"])
print(review[mask])

     Review ID Review Date                                     Review Content  \
0      4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
1     25329416  2013-11-03  Me and my friends had such a nice time at Dott...   
3     41133812  2012-05-08  The apartment was situated on the first floor ...   
7     10787310  2013-06-02  Carolines room is perfectly located to discove...   
10    24326991  2014-10-19  Many thanks Annabel, our stay was perfect! We ...   
..         ...         ...                                                ...   
967   31488970  2014-10-18  Serena was very welcoming and the place was qu...   
970    1211808  2014-03-08  It was such a shame that we were only able to ...   
971   21709517  2013-07-03  Anders is a great host. The flat is exactly as...   
985   29498170  2013-12-17  The neighborhood was pretty central and my fri...   
987   21950610  2013-06-10  Arne's studio was the perfect size and locatio...   

                           

In [176]:
mask = review["Room Price"].between(80,100)
review[mask]

Review ID Review Date                                     Review Content  \
0      4055629  2012-10-06  Very nice accommodation in an aesthetically pl...   
1     25329416  2013-11-03  Me and my friends had such a nice time at Dott...   
17     7568387  2013-02-01  Kristina and Ekaterine were lovley hosts. They...   
20    38360407  2013-12-31  Nice contact. Very friendly and supportive. Th...   
23    40294978  2012-09-25  The room was nice, breakfast was great and Joh...   
..         ...         ...                                                ...   
986   38974125  2014-11-29  The host canceled this reservation 2 days befo...   
991   35585745  2012-12-30  Andrea was good in communication and flexible ...   
992   13423090  2014-12-25  Ca' di paolo is a cozy apartment in a great lo...   
993   27392171  2012-03-07  What a great place to stay! In the heart of Ma...   
997   46642535  2014-08-30  John was a great host.  I came in on a red eye...   

                           Listing Title  \
0    Nottinghill Portobello  Artist Flat   
1     Quiet Pink Studio in the PIJP area   
17   Hollywood Furnished Private Bedroom   
20   Curved wall Studio ST4 with Kitchen   
23    Dupont Private Room Meridian Manor   
..                                   ...   
986       Cozy and Heart of Downtown MTL   
991           Designer Inner City Escape   
992                         ca' di paolo   
993    Charming Studio - Heart of Marais   
997      Top Floor Renovated 1 BR / 1BA    

                                  Neighbourhood         City            State  \
0                        Kensington and Chelsea       London          England   
1                       De Pijp - Rivierenbuurt    Amsterdam    North Holland   
17                                    Hollywood  Los Angeles       California   
20                                Tower Hamlets       London          England   
23   Dupont Circle, Connecticut Avenue/K Street   Washington             D.C.   
..                                          ...          ...              ...   
986                                 Ville-Marie     Montreal           Quebec   
991                                      Sydney       Sydney  New South Wales   
992                                    Castello       Venice           Veneto   
993                                      Temple        Paris    Île-de-France   
997                                West Roxbury       Boston    Massachusetts   

                                 Country        Room Type  Room Price  \
0                         United Kingdom  Entire home/apt         100   
1                        The Netherlands     Private room          80   
17                         United States     Private room          99   
20                        United Kingdom  Entire home/apt          85   
23   District of Columbia, United States     Private room          99   
..                                   ...              ...         ...   
986                               Canada  Entire home/apt          80   
991                            Australia  Entire home/apt          98   
992                                Italy  Entire home/apt          99   
993                               France  Entire home/apt          95   
997                        United States  Entire home/apt          95   

     Room Availability  
0                  338  
1                   10  
17                 244  
20                 344  
23                 361  
..                 ...  
986                137  
991                319  
992                303  
993                284  
997                 10  

[196 rows x 11 columns]

In [178]:
mask = review["Review Date"].between("2013-01-01","2014-01-01")
review[mask]

Review ID Review Date                                     Review Content  \
1     25329416  2013-11-03  Me and my friends had such a nice time at Dott...   
4      7465026  2013-08-16  Even though it was only for one night, we had ...   
6     20417380  2013-11-07  Wonderful experience. We loved staying in the ...   
7     10787310  2013-06-02  Carolines room is perfectly located to discove...   
9     15542291  2013-12-28  What a wonderful location, right in the heart ...   
..         ...         ...                                                ...   
983    2018617  2013-12-22  Ysaira and Jose are the sweetest people. They ...   
985   29498170  2013-12-17  The neighborhood was pretty central and my fri...   
987   21950610  2013-06-10  Arne's studio was the perfect size and locatio...   
996   30544438  2013-02-28  Highly recommend this as a place to stay if yo...   
999   38944752  2013-10-15  Thank you for the wonderful stay!   It was a c...   

                           Listing Title            Neighbourhood  \
1     Quiet Pink Studio in the PIJP area  De Pijp - Rivierenbuurt   
4          Acropolis Apartment brand new                 ΑΚΡΟΠΟΛΗ   
6     LARGE HOME FOR GROUP ACCOMMODATION              Stonnington   
7          Private room - Central London              Westminster   
9          Athens Acropolis /B 'Luxury 2   ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ   
..                                   ...                      ...   
983     Bronx Room Near Yankees & Harlem           Morris Heights   
985           Great Room at the Gran Via                  Palacio   
987  Stylish app. in center of Amsterdam             Centrum-Oost   
996     The Venice Roost on Abbot Kinney                   Venice   
999            15 Minutes from Manhattan                 Woodside   

              City                State          Country        Room Type  \
1        Amsterdam        North Holland  The Netherlands     Private room   
4           Athens               Attica           Greece  Entire home/apt   
6        Melbourne             Victoria        Australia  Entire home/apt   
7           London              England   United Kingdom     Private room   
9           Athens               Attica           Greece  Entire home/apt   
..             ...                  ...              ...              ...   
983  New York City             New York    United States     Private room   
985         Madrid  Comunidad de Madrid            Spain     Private room   
987      Amsterdam        North Holland  The Netherlands  Entire home/apt   
996    Los Angeles           California    United States  Entire home/apt   
999  New York City             New York    United States     Private room   

     Room Price  Room Availability  
1            80                 10  
4            62                281  
6           248                239  
7            60                351  
9            37                329  
..          ...                ...  
983          40                302  
985          30                338  
987         115                255  
996         191                309  
999         110                329  

[336 rows x 11 columns]

In [179]:
review.sort_values("City", inplace=True)
review["City"]

409     Amsterdam
912     Amsterdam
770     Amsterdam
168     Amsterdam
782     Amsterdam
          ...    
839    Washington
139    Washington
128    Washington
589    Washington
437    Washington
Name: City, Length: 1000, dtype: object

In [180]:
review["City"].duplicated()

409    False
912     True
770     True
168     True
782     True
       ...  
839     True
139     True
128     True
589     True
437     True
Name: City, Length: 1000, dtype: bool

In [184]:
mask = ~review["City"].duplicated()
review[mask]["City"]

409        Amsterdam
772          Antwerp
648           Athens
758           Austin
135        Barcelona
77            Berlin
508           Boston
250         Brussels
199          Chicago
877           London
799      Los Angeles
297           Madrid
83         Melbourne
498         Montreal
47         Nashville
21       New Orleans
643    New York City
292          Oakland
927            Paris
830         Portland
896    San Francisco
965          Seattle
472           Sydney
220          Toronto
278           Venice
420           Vienna
450       Washington
Name: City, dtype: object

In [185]:
print(len(review))

1000


In [186]:
print(len(review.drop_duplicates()))

1000


In [187]:
print(len(review.drop_duplicates(subset=["City"])))

27


In [188]:
len(review.drop_duplicates(subset=["Room Type"]))

3

In [189]:
#unique, nunique methods
review["City"]

409     Amsterdam
912     Amsterdam
770     Amsterdam
168     Amsterdam
782     Amsterdam
          ...    
839    Washington
139    Washington
128    Washington
589    Washington
437    Washington
Name: City, Length: 1000, dtype: object

In [190]:
review["City"].unique()

array(['Amsterdam', 'Antwerp', 'Athens', 'Austin', 'Barcelona', 'Berlin',
       'Boston', 'Brussels', 'Chicago', 'London', 'Los Angeles', 'Madrid',
       'Melbourne', 'Montreal', 'Nashville', 'New Orleans',
       'New York City', 'Oakland', 'Paris', 'Portland', 'San Francisco',
       'Seattle', 'Sydney', 'Toronto', 'Venice', 'Vienna', 'Washington'],
      dtype=object)

In [191]:
len(review["City"].unique())

27

In [192]:
type(review["City"].unique())

numpy.ndarray

In [193]:
review["City"].nunique() #number of unique

27

In [195]:
review["Country"]
# upper(), lower(), title(), len()

409                        The Netherlands
912                        The Netherlands
770                        The Netherlands
168                        The Netherlands
782                        The Netherlands
                      ...                 
839    District of Columbia, United States
139    District of Columbia, United States
128    District of Columbia, United States
589    District of Columbia, United States
437    District of Columbia, United States
Name: Country, Length: 1000, dtype: object

In [196]:
review["Country"].str.upper()

409                        THE NETHERLANDS
912                        THE NETHERLANDS
770                        THE NETHERLANDS
168                        THE NETHERLANDS
782                        THE NETHERLANDS
                      ...                 
839    DISTRICT OF COLUMBIA, UNITED STATES
139    DISTRICT OF COLUMBIA, UNITED STATES
128    DISTRICT OF COLUMBIA, UNITED STATES
589    DISTRICT OF COLUMBIA, UNITED STATES
437    DISTRICT OF COLUMBIA, UNITED STATES
Name: Country, Length: 1000, dtype: object

In [197]:
review["Country"].str.lower()

409                        the netherlands
912                        the netherlands
770                        the netherlands
168                        the netherlands
782                        the netherlands
                      ...                 
839    district of columbia, united states
139    district of columbia, united states
128    district of columbia, united states
589    district of columbia, united states
437    district of columbia, united states
Name: Country, Length: 1000, dtype: object

In [198]:
review["Country"].str.title()

409                        The Netherlands
912                        The Netherlands
770                        The Netherlands
168                        The Netherlands
782                        The Netherlands
                      ...                 
839    District Of Columbia, United States
139    District Of Columbia, United States
128    District Of Columbia, United States
589    District Of Columbia, United States
437    District Of Columbia, United States
Name: Country, Length: 1000, dtype: object

In [202]:
print(len("benim adim deneme"))
print(len(review["Country"]))
print(review["Country"].str.len())

17
1000
409    15
912    15
770    15
168    15
782    15
       ..
839    35
139    35
128    35
589    35
437    35
Name: Country, Length: 1000, dtype: int64


In [211]:
print("arin yazilim".replace("i","I"))
x = "itu ıtu Itu"
y = ["itu","ıtu","Itu"]
for i in y:
    print(x.replace(i,"itü"))

arIn yazIlIm
itü ıtu Itu
itu itü Itu
itu ıtu itü


In [212]:
print(review["Room Type"].str.replace("room","Room"))

409       Private Room
912    Entire home/apt
770    Entire home/apt
168    Entire home/apt
782    Entire home/apt
            ...       
839    Entire home/apt
139    Entire home/apt
128    Entire home/apt
589    Entire home/apt
437        Shared Room
Name: Room Type, Length: 1000, dtype: object


In [214]:
mask = review["City"].str.upper().str.contains("YORK")
review[mask]

Review ID Review Date                                     Review Content  \
643    7159670  2013-07-06  We had a great time staying with Leo! She was ...   
644    9955391  2012-03-17  A great spot, perfect for mid-town business or...   
18     9329281  2013-12-03  This is not our first time to NYC, but this is...   
664   28026267  2014-08-23  Anna made us feel welcome and provided some su...   
255   10080005  2013-06-11  We had a great stay at michaels place. He was ...   
..         ...         ...                                                ...   
265   32062377  2014-07-03  We had a very friendly welcome from Isaac who ...   
560     151811  2014-03-05  My stay at Tama's apartment couldn't have been...   
361    4639476  2013-09-26  Amy was very accommodating and easy to get a h...   
611   32698671  2013-01-10  Josephine was a great host and the apartment i...   
270   41405493  2014-09-18  It is very unique and pleasant staying. We wer...   

                           Listing Title       Neighbourhood           City  \
643   Private room for 2 + couch—Chelsea             Chelsea  New York City   
644        1 BDR in MIDTOWN DESIGNER APT             Midtown  New York City   
18    FANTASTIC TIMES SQUARE ONE BEDROOM    Theater District  New York City   
664  Boutique Alcoves Studio by Union Sq   Greenwich Village  New York City   
255   Beautiful Room for Rent in Astoria             Astoria  New York City   
..                                   ...                 ...            ...   
265     Architect designed 2000ft duplex  Bedford-Stuyvesant  New York City   
560  Quiet, Private BR W/BA, + Amenities              Harlem  New York City   
361    Apartment in a Private Brownstone         East Harlem  New York City   
611      Very Large & Serene Artist Loft     Lower East Side  New York City   
270  Gorgeous Entire Manhattan Townhouse              Harlem  New York City   

        State        Country        Room Type  Room Price  Room Availability  
643  New York  United States     Private room          65                 45  
644  New York  United States     Private room         125                296  
18   New York  United States  Entire home/apt         260                291  
664  New York  United States  Entire home/apt         149                243  
255  New York  United States     Private room          96                269  
..        ...            ...              ...         ...                ...  
265  New York  United States  Entire home/apt         220                235  
560  New York  United States     Private room         135                326  
361  New York  United States  Entire home/apt         150                246  
611  New York  United States  Entire home/apt         420                344  
270  New York  United States  Entire home/apt         199                  3  

[135 rows x 11 columns]

In [215]:
mask = review["City"].str.upper().str.startswith("LOS")
review[mask]

Review ID Review Date                                     Review Content  \
799    5239947  2013-01-15  The only issue that we had was that the elevat...   
774   33501216  2012-09-22  Sandra was very welcoming and helpful with all...   
430   40152723  2013-10-12  Lara is a great host and the place was as desc...   
415   37920920  2013-05-03  Munkhzul gives me a easy and simple walk thru....   
913   37186607  2014-01-28  Blithe is a great host!  She made sure we had ...   
..         ...         ...                                                ...   
17     7568387  2013-02-01  Kristina and Ekaterine were lovley hosts. They...   
258   31118183  2014-09-04  Mike was a gracious host and he was very accom...   
247   26697787  2013-12-06  Taylor was a great host and always easily cont...   
236   45372449  2012-09-12  Our stay in the room was pleasant and it fit t...   
230   40410663  2013-10-17  Victoria was great, it was a last min thing fo...   

                           Listing Title    Neighbourhood         City  \
799    Amazing hillside 4 bdrm 4k  sq ft    Monterey Park  Los Angeles   
774  Escape to & Relax 4 blocks to Beach    Playa del Rey  Los Angeles   
430   Treehouse Futon/Loft By The Beach!       Long Beach  Los Angeles   
415    Cozy 2 bdr/2b apt + parking, pool         Torrance  Los Angeles   
913  2-level 2-bdrm, pool/jacuzzi, more!  Atwater Village  Los Angeles   
..                                   ...              ...          ...   
17   Hollywood Furnished Private Bedroom        Hollywood  Los Angeles   
258       Pvt Room gated parking in NOHO   Valley Village  Los Angeles   
247      Luxurious Venice Beach Bungalow           Venice  Los Angeles   
236     Starlight Room With 2 Queen Beds      Pico Rivera  Los Angeles   
230                    Le Petit Bungalow           Venice  Los Angeles   

          State        Country        Room Type  Room Price  Room Availability  
799  California  United States  Entire home/apt        1500                365  
774  California  United States     Private room          95                127  
430  California  United States     Private room          58                365  
415  California  United States  Entire home/apt         105                 80  
913  California  United States  Entire home/apt         116                117  
..          ...            ...              ...         ...                ...  
17   California  United States     Private room          99                244  
258  California  United States     Private room          55                258  
247  California  United States  Entire home/apt         179                351  
236  California  United States     Private room          59                350  
230  California  United States  Entire home/apt         140                356  

[68 rows x 11 columns]

In [219]:
mask = review["City"].str.upper().str.endswith("DON")
review[mask]

Review ID Review Date                                     Review Content  \
877    1086998  2013-10-23  My partner and I had to move to London in late...   
10    24326991  2014-10-19  Many thanks Annabel, our stay was perfect! We ...   
547    7838623  2014-11-09  I can only speak very positively of our experi...   
311   21450174  2012-02-06  Great place for a London weekend trip. Clean a...   
302    5768056  2013-06-04  Linda has a lovely home, very cozy and you get...   
..         ...         ...                                                ...   
254    7107083  2012-09-27  I really enjoyed staying at this apartment. Ma...   
20    38360407  2013-12-31  Nice contact. Very friendly and supportive. Th...   
267   12386330  2012-12-12  Gabriele was a great host -- provided fantasti...   
146   44846244  2013-04-14  Sevtap and her husband were wery kind. We were...   
860   29252683  2012-07-17  Great apartment and great location. Close to e...   

                           Listing Title           Neighbourhood    City  \
877      Double Room in  Edwardian House                  Ealing  London   
10       Light 2 bedroom in Notting Hill  Kensington and Chelsea  London   
547     Stylish Central London Apartment                 Lambeth  London   
311     Elegant & cozy double & bathroom                  Sutton  London   
302    Beautiful flat in Victorian house                 Hackney  London   
..                                   ...                     ...     ...   
254     COVENT GARDEN ONE BEDROOM STUDIO             Westminster  London   
20   Curved wall Studio ST4 with Kitchen           Tower Hamlets  London   
267          DOUBLE ROOM CLAPHAM(ZONE 2)                 Lambeth  London   
146      A Lovely room in West Hampstead                  Camden  London   
860   Gorgeous Covent Garden Uber Modern             Westminster  London   

       State         Country        Room Type  Room Price  Room Availability  
877  England  United Kingdom     Private room          49                360  
10   England  United Kingdom  Entire home/apt         140                151  
547  England  United Kingdom  Entire home/apt         110                278  
311  England  United Kingdom     Private room          35                322  
302  England  United Kingdom  Entire home/apt         110                 19  
..       ...             ...              ...         ...                ...  
254  England  United Kingdom  Entire home/apt          90                349  
20   England  United Kingdom  Entire home/apt          85                344  
267  England  United Kingdom     Private room          55                365  
146  England  United Kingdom     Private room          40                345  
860  England  United Kingdom  Entire home/apt         245                245  

[104 rows x 11 columns]

In [220]:
# str.strip()    sol ve sağdaki boşluktan kurtul
# str.lstrip()   soldaki boşluktan kurtul
# str.rstrip()   ağdaki boşluktan kurtul
# str.split("-",) belirtilen bölümlere göre listeye çeviriyor (örnekte -'ye göre)

In [222]:
review.head(10)
#review["City"].str.split(' ').str.get(0)  -> python listesi
#review["City"].str.split(' ', expand=True)  -> dataframe

Review ID Review Date                                     Review Content  \
409   40057065  2014-08-21  Borja was a great host! He made sure I knew ho...   
912   15406715  2014-06-29  We felt truly welcomed to Nina & Remy's home. ...   
770   41199627  2012-06-17  Pauline's home was beautiful and just as you s...   
168   21899385  2013-01-18  Our host Karmen was very courteous to us from ...   
782   17887404  2013-02-07  Staying at Sigrid's apartment was wonderful. S...   
162   11554752  2014-02-12  I had a terrific stay at Sharon's apartment.  ...   
951   32808889  2014-04-13  The apartment was exactly as advertised. We ha...   
948   20984994  2012-09-28  We had a lovely stay at this cosy & very authe...   
802    9598457  2012-03-09  Marnix was a great host! Really easy to contac...   
946   28194838  2013-06-05  Nice studio apartment right on the corner of a...   

                           Listing Title  \
409   Spacious room near the city centre   
912   Spacious&historic apartment@canals   
770  Cozy apt, fab view, next to centre!   
168      2-Bedroom apartment with garden   
782  Perfect nice apartment top location   
162  Peaceful in the Pijp for One Person   
951  Central Lux flat with Roof-Terrace!   
948   Casita Sumita @ the Brouwersgracht   
802          Light & Spacious Houseboat    
946    Cozy Apartment in Jordaan @ Canal   

                              Neighbourhood       City          State  \
409                           Bos en Lommer  Amsterdam  North Holland   
912                            Centrum-West  Amsterdam  North Holland   
770                  De Baarsjes - Oud-West  Amsterdam  North Holland   
168                           Bos en Lommer  Amsterdam  North Holland   
782                                    Zuid  Amsterdam  North Holland   
162                 De Pijp - Rivierenbuurt  Amsterdam  North Holland   
951                              Westerpark  Amsterdam  North Holland   
948                            Centrum-West  Amsterdam  North Holland   
802  Oostelijk Havengebied - Indische Buurt  Amsterdam  North Holland   
946                              Westerpark  Amsterdam  North Holland   

             Country        Room Type  Room Price  Room Availability  
409  The Netherlands     Private room          97                271  
912  The Netherlands  Entire home/apt          99                  0  
770  The Netherlands  Entire home/apt          85                271  
168  The Netherlands  Entire home/apt          95                124  
782  The Netherlands  Entire home/apt          75                301  
162  The Netherlands     Private room          55                325  
951  The Netherlands  Entire home/apt         120                107  
948  The Netherlands  Entire home/apt          60                 18  
802  The Netherlands  Entire home/apt         210                239  
946  The Netherlands  Entire home/apt          99                  6