In [1]:
print("Hello World")

Hello World


# Başlık1
## Başlık2
### Başlık3
deneme

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [13]:
import time

In [26]:
k = np.array([1,2,3,4,5,6])
k

array([1, 2, 3, 4, 5, 6])

In [22]:
start_time = time.time()
A= np.array(50000000)
A ** 2
time1 = time.time() - start_time
start_time2 = time.time()
L = range(50000000)
[i ** 2 for i in L]
time2 = time.time() - start_time2

print(time2/time1)

155241.73747841106


In [27]:
x = np.array([4,5,6,7])
print(x)

[4 5 6 7]


In [28]:
print(type(x))
print(x.shape)
print(x.size)
print(x.ndim)
print(x.nbytes)
print(x.dtype)

<class 'numpy.ndarray'>
(4,)
4
1
32
int64


In [31]:
t = np.array([[1,2,3],[4,5,6]])
y = t
print(y)
print(type(y))
print(y.shape)
print(y.size)
print(y.ndim)
print(y.nbytes)
print(y.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2
48
int64


In [32]:
z = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
y = z
print(y)
print(type(y))
print(y.shape)
print(y.size)
print(y.ndim)
print(y.nbytes)
print(y.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)
12
3
96
int64


In [36]:
x = np.array([1,"2",3])
print(x.dtype)

<U21


In [39]:
x = np.array([1,2.0,3], dtype=np.complex)
print(x.dtype)
print(x)

complex128
[1.+0.j 2.+0.j 3.+0.j]


In [41]:
x = np.array([1.2,2.7,3.8], dtype=np.int)
print(x)
print(x.dtype)

[1 2 3]
int64


In [44]:
x = np.array(x, dtype=float)
print(x)
print(x.dtype)

[1. 2. 3.]
float64


In [46]:
x = x.astype(np.int)
print(x)

[1 2 3]


In [48]:
x1 = np.array([1,2,3],dtype=np.int)
x2 = np.array([5.2,2.8,4.9],dtype=np.float)

print(x1+x2)
print((x1+x2).dtype)

[6.2 4.8 7.9]
float64


In [55]:
x = np.sqrt(np.array([-1,9,4], dtype=np.complex))
print(x)
print(x.dtype)
print(type(x))
print(x.real)
print(x.imag)
print(x.real.dtype)
print(x.imag.dtype)

[0.+1.j 3.+0.j 2.+0.j]
complex128
<class 'numpy.ndarray'>
[0. 3. 2.]
[1. 0. 0.]
float64
float64


In [56]:
np.save('ndarray_1',x)

In [58]:
y = np.load('ndarray_1.npy')
print(y)
print(y.shape)

[0.+1.j 3.+0.j 2.+0.j]
(3,)


In [59]:
x1 = np.zeros(4)
print(x1)
print(x1.dtype)
x2 = np.ones(4)
print(x2)
print(x2.dtype)

[0. 0. 0. 0.]
float64
[1. 1. 1. 1.]
float64


In [64]:
x1 = np.zeros((2,3,4), dtype=np.int)
print(x1)
print(x1.dtype)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
int64


In [65]:
x = np.full((2,3),10)
print(x)

[[10 10 10]
 [10 10 10]]


In [66]:
x = np.empty((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [67]:
x.fill(3)
print(x)

[[3. 3.]
 [3. 3.]]


In [70]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [71]:
y = np.eye(5,4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [73]:
x = np.eye(6)
print(x)
y = np.eye(6,k=3)
print(y)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [75]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [77]:
x = np.diag([3,4,7,11])
print(x)

[[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0  7  0]
 [ 0  0  0 11]]


In [78]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [79]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [80]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [82]:
x = np.linspace(0,15,10)
x

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [89]:
x = np.linspace(0,25, endpoint=False)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5])

In [90]:
x = np.arange(20)
print(x)

x = np.reshape(x, (4,5))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [96]:
x = np.linspace(0,19,20)
print(x)

y = np.reshape(x, (2,10))
print(y)
print(x.size)
print(y.size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
20
20


In [98]:
z = np.linspace(0,19,20).reshape(2,10)
print(z)


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [104]:
x = np.random.random((2,3))
x

array([[0.64909577, 0.47861897, 0.89611385],
       [0.10076378, 0.2640292 , 0.58770533]])

In [110]:
x = np.random.randint(3,12, size=(3,2))
x

array([[ 7,  5],
       [10, 10],
       [ 5,  4]])

In [113]:
x = np.arange(5)
print(x)
print(x[2])
print(x[-3])

[0 1 2 3 4]
2
2


In [115]:
x[2] = 200
x

array([  0,   1, 200,   3,   4])

In [116]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
x[0,1]
x[0,3],x[2,2] = 300,600
x

array([[  0,   1,   2, 300],
       [  4,   5,   6,   7],
       [  8,   9, 600, 600]])

In [124]:
x = np.arange(6)
print(x)
y = np.delete(x, [0,3])
print(x)
print(y)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[1 2 4 5]


# axis = 0 -> row (satır), axis = 1 -> column (sütun)

In [128]:
x = np.arange(16).reshape(4,4)
print(x)
x = np.delete(x,1,axis=0)
print(x)
x = np.delete(x,1,axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  3]
 [ 8 10 11]
 [12 14 15]]


In [129]:
x = np.arange(16).reshape(4,4)
print(x)
x = np.delete(x, [0,2], axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [132]:
x = np.arange(5)
print(x)
x = np.append(x,100)
print(x)
x = np.append(x,[200,300])
print(x)

[0 1 2 3 4]
[  0   1   2   3   4 100]
[  0   1   2   3   4 100 200 300]


In [136]:
x = np.arange(9).reshape(3,3)
print(x)
x = np.append(x,[[100,200,300]], axis = 0)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


In [140]:
x = np.append(x,[[10],[20],[30],[40]], axis = 1)
print(x)

[[  0   1   2  10]
 [  3   4   5  20]
 [  6   7   8  30]
 [100 200 300  40]]


In [143]:
#np.insert ---> np.insert(ndarray, index, element, axis)
x = np.arange(5)
print(x)
x= np.insert(x,0,10)
print(x)

[0 1 2 3 4]
[10  0  1  2  3  4]


In [144]:
x= np.insert(x,2,[300,400])
print(x)

[ 10   0 300 400   1   2   3   4]


In [152]:
x = np.arange(9).reshape(3,3)
print(x)
y = np.insert(x,1,[100,200,300], axis=0)
print(y)
y = np.insert(x,0,[100,200,300], axis=1)
print(y)
y = np.insert(x,0,[100], axis=1)
print(y)
y = np.insert(x,0,[[100],[200]], axis=1)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]
[[100   0   1   2]
 [200   3   4   5]
 [300   6   7   8]]
[[100   0   1   2]
 [100   3   4   5]
 [100   6   7   8]]
[[100 200   0   1   2]
 [100 200   3   4   5]
 [100 200   6   7   8]]


In [158]:
x = np.arange(3)
print(x)

y = np.arange(9).reshape(3,3)
print(y)

z = np.vstack((x,y))
print(z)

y = y.reshape(9,)
print(y)

t = np.hstack((x,y))
print(t)

#np.stack

[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 0 1 2 3 4 5 6 7 8]


In [163]:
x = np.arange(10)
print(x)
print(x[2:6])
print(x[4:])
print(x[:7])
print(x[:-1])
print(x[-4:-2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]
[6 7]


In [162]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [169]:
x = np.arange(25).reshape(5,5)
print(x,"\n")
y = x[0:3,1:4]
print(y,"\n")

z = x[2:]
print(z,"\n")

t = x[::]
print(t,"\n")

v = x[:,3:]
print(v)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [174]:
x = np.arange(9).reshape(3,3)
print(x,"\n")

y = x[1:2,0:2]
print(y)
y[0,0] = 100
print(x,"\n")

print(np.shares_memory(x,y))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4]]
[[  0   1   2]
 [100   4   5]
 [  6   7   8]] 

True


In [179]:
x = np.arange(16).reshape(4,4)
print(x)
print()
y = np.copy(x[0:3,1:3])
print(y)
print()
y[0,1] = 500
print(x)
print()
print(y)
print()
z = x[1:2,1:2].copy()
print(z)
print(np.shares_memory(x,z))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[  1 500]
 [  5   6]
 [  9  10]]

[[5]]
False


In [186]:
x = np.linspace(1,19,10).reshape(2,5)
print(x.size)
print(x)

10
[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]]


In [188]:
x = np.linspace(1,21,11)
print(x.size)
print(x)
y = np.array([2,4,7])
print(y)
print(x[y])

11
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[2 4 7]
[ 5.  9. 15.]


In [193]:
x = np.arange(25).reshape(5,5)
print(x)
y = np.array([1,2])
print(y)
print()
print(x[y,:])

# fancy indexing

z = x[y,:]
print(z)
z[0,0] = 100
print()
print(z)
print()
print(x)

print(np.shares_memory(x,z))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[1 2]

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]

[[100   6   7   8   9]
 [ 10  11  12  13  14]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False


In [196]:
# boolean indezing

x = np.arange(10)
print(x)
print()
z = x[(x % 2 == 0)]
print(z)
print()
z[0] = 10
print(z)
print()
print(x)
print()

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]

[10  2  4  6  8]

[0 1 2 3 4 5 6 7 8 9]



In [245]:
x = np.random.randint(10,size=10)
y = np.random.randint(2,size=10)
print(x)
print(y)
print(x>y)
print(type(x>y))
print((x>y).dtype)

print(np.all(x>y))
print(np.any(x>y))

[2 5 9 6 9 9 5 2 7 2]
[1 1 0 1 0 1 1 1 0 0]
[ True  True  True  True  True  True  True  True  True  True]
<class 'numpy.ndarray'>
bool
True
True


In [251]:
x = np.linspace(1,21,11)
print(x)
mask = (x % 3 == 0)
print(mask)
print(type(mask))
print(x[mask])
x[mask] = 1
print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[False  True False False  True False False  True False False  True]
<class 'numpy.ndarray'>
[ 3.  9. 15. 21.]
[ 1.  1.  5.  7.  1. 11. 13.  1. 17. 19.  1.]


In [254]:
x = np.array([2,5,3,6,9])
y = np.array([6,1,8,7,3])

z = np.intersect1d(x,y)

print(type(z))

<class 'numpy.ndarray'>


In [256]:
print(np.setdiff1d(x,y))
print(np.setdiff1d(y,x))

[2 5 9]
[1 7 8]


In [257]:
print(np.union1d(x,y))

[1 2 3 5 6 7 8 9]


In [258]:
print(np.in1d(x,y))

[False False  True  True False]


In [259]:
x = np.array([2,5,3,6,9,4,3,6,5,0])
print(np.unique(x))

[0 2 3 4 5 6 9]


In [268]:
#sort

x = np.random.randint(1,10,size=(10,))
print(x)
print(np.sort(x))
print(x)
print()

y = np.random.randint(1,10, size=(10,))
print(y)
y.sort()
print(y)

[4 7 4 1 6 4 3 5 4 1]
[1 1 3 4 4 4 4 5 6 7]
[4 7 4 1 6 4 3 5 4 1]

[6 1 3 4 8 4 9 9 7 6]
[1 3 4 4 6 6 7 8 9 9]


In [271]:
x = np.random.randint(1,10, size = (5,5))
print(x)
print()
print(np.sort(x,axis=0))
print()
print(np.sort(x,axis=1))
print()

[[1 1 1 8 3]
 [9 7 7 3 9]
 [7 2 7 6 2]
 [6 9 3 8 2]
 [5 3 6 3 6]]

[[1 1 1 3 2]
 [5 2 3 3 2]
 [6 3 6 6 3]
 [7 7 7 8 6]
 [9 9 7 8 9]]

[[1 1 1 3 8]
 [3 7 7 9 9]
 [2 2 6 7 7]
 [2 3 6 8 9]
 [3 3 5 6 6]]



In [278]:
x = np.random.randint(1,10,size=(5,))
y = np.random.randint(1,10,size=(5,))
print(x)
print(y)

print(x+y)
print(np.add(x,y))
print(type(x+y))
print(type(np.add(x,y)))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

[8 4 4 7 3]
[3 3 5 1 8]
[11  7  9  8 11]
[11  7  9  8 11]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 5  1 -1  6 -5]
[ 5  1 -1  6 -5]
[24 12 20  7 24]
[24 12 20  7 24]
[2.66666667 1.33333333 0.8        7.         0.375     ]
[2.66666667 1.33333333 0.8        7.         0.375     ]


In [280]:
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x == y)

[11  7  7 10  6]
[5 1 1 4 0]
[24 12 12 21  9]
[2.66666667 1.33333333 1.33333333 2.33333333 1.        ]
[False False False False False]


In [281]:
print(np.array_equal(x,y))

False


In [288]:
print(np.sqrt(x))
print(np.power(x,3))
print(x)
print(np.exp(x))


[2.82842712 2.         2.         2.64575131 1.73205081]
[512  64  64 343  27]
[8 4 4 7 3]
[2980.95798704   54.59815003   54.59815003 1096.63315843   20.08553692]


In [291]:
x = np.random.randint(1,10,size=(3,3))
print(x)
print(np.sum(x))
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.min())
print(x.max())
print(x.argmin()) # min elemanın index sırası
print(x.argmax()) # max elemanın index sırası

[[3 3 4]
 [6 5 2]
 [8 8 1]]
40
[17 16  7]
[10 13 17]
1
8
8
6


In [295]:
x = np.random.randint(1,10,size=(8,))
print(x)
print()
print(x.mean())
print()
print(np.median(x))
print()
print(x.std())
print()

[7 2 6 1 8 6 6 3]

4.875

6.0

2.368411915187052



In [301]:
y = np.random.randint(1,10,size=(4,3))
print(y)
print()
print(y.mean(axis=0))
print()
print(y.mean(axis=1))
print()
print(y.std(axis=0))

[[5 6 9]
 [8 7 9]
 [3 5 3]
 [5 6 1]]

[5.25 6.   5.5 ]

[6.66666667 8.         3.66666667 4.        ]

[1.78535711 0.70710678 3.57071421]


In [305]:
x = np.random.randint(1,10,size=(1,))
y = np.random.randint(1,10,size=(3,2))
print(x)
print()
print(y)
print()
print(x+y)

[7]

[[6 4]
 [5 5]
 [2 6]]

[[13 11]
 [12 12]
 [ 9 13]]


In [307]:
x = np.zeros(5)
y = np.ones(5)
print(x)
print(y)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [308]:
x = np.arange(7,42,2)
print(x)

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [311]:
x = np.linspace(1,10,16).reshape(4,4)
print(x)

[[ 1.   1.6  2.2  2.8]
 [ 3.4  4.   4.6  5.2]
 [ 5.8  6.4  7.   7.6]
 [ 8.2  8.8  9.4 10. ]]


In [314]:
x = np.random.randint(1,10,size=(4,4))
print(x)

[[5 4 1 7]
 [1 4 8 5]
 [2 7 7 2]
 [7 4 4 4]]


In [315]:
x = np.linspace(0.1,1,10)
print(x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [318]:
x = np.arange(25).reshape(5,5)
print(x[1:3,2:4])

[[ 7  8]
 [12 13]]


In [320]:
x = np.arange(1,17).reshape(4,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [325]:
y = x[:,[1,3]].reshape(2,4) 
# y = x[x%2==0].reshaper(2,4)
print(y)

[[ 2  4  6  8]
 [10 12 14 16]]


In [329]:
A = np.array([[1,1],[5,10]])
B = np.array([100,700])
print(A)
print()
print(B)
print()
x = np.linalg.solve(A,B)
print(x)

[[ 1  1]
 [ 5 10]]

[100 700]

[60. 40.]


In [331]:
x = np.random.randint(1,5,4)
print(x)
y = np.random.randint(1,5,4)
print(y)
print()
print(np.dot(x,y))

[1 4 3 1]
[2 2 1 2]

15


In [332]:
x = np.random.randint(1,5,size = (2,2))
print(x)
y = np.random.randint(1,5,size = (2,2))
print(y)
print()
print(np.dot(x,y))

[[3 3]
 [3 1]]
[[1 3]
 [4 1]]

[[15 12]
 [ 7 10]]


In [333]:
print(pd.__version__)

1.1.4
